config/routes.rb
Blog::Application.routes.draw do

  get "sessions/new"
  get "users/new"
  get 'links', to: 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  resources :baskets

  resources :products do
    collection do
      post 'addtobasket'
    end
  end
  resources :posts
  resources :guestbooks

  get "home/index"

   resources :home
   root 'home#index'

  

end

app/models/guestbook.rb
class Guestbook < ActiveRecord::Base
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  before_action :set_guestbook, only: [:show, :edit, :update, :destroy]

  # GET /guestbooks
  # GET /guestbooks.json
  def index
    @guestbooks = Guestbook.all
  end

  # GET /guestbooks/1
  # GET /guestbooks/1.json
  def show
  end

  # GET /guestbooks/new
  def new
    @guestbook = Guestbook.new
  end

  # GET /guestbooks/1/edit
  def edit
  end

  # POST /guestbooks
  # POST /guestbooks.json
  def create
    @guestbook = Guestbook.new(guestbook_params)

    respond_to do |format|
      if @guestbook.save
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guestbook }
      else
        format.html { render action: 'new' }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guestbooks/1
  # PATCH/PUT /guestbooks/1.json
  def update
    respond_to do |format|
      if @guestbook.update(guestbook_params)
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbooks/1
  # DELETE /guestbooks/1.json
  def destroy
    @guestbook.destroy
    respond_to do |format|
      format.html { redirect_to guestbooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guestbook
      @guestbook = Guestbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guestbook_params
      params.require(:guestbook).permit(:message, :name)
    end
end

app/helpers/guestbook_helper.rb
module GuestbookHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/views/guestbooks/_form.html.erb
<%= form_for(@guestbook) do |f| %>
  <% if @guestbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guestbook.errors.count, "error") %> prohibited this guestbook from being saved:</h2>

      <ul>
      <% @guestbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guestbooks/edit.html.erb
<h1>Editing guestbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @guestbook %> |
<%= link_to 'Back', guestbooks_path, 'data-no-turbolink' => true  %>

app/views/guestbooks/index.html.erb
<h1><%= t('guestbook') %></h1>

<table id="#guestbookMessages">
  <thead>
    <tr>
      <th><%= t('message') %></th>
      <th><%= t('name') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @guestbooks.each do |guestbook| %>
      <tr>
        <td><%= guestbook.message %></td>
        <td><%= guestbook.name %></td>
        <td><%= link_to t('show'), guestbook, class: 'btn btn-info' %></td>
        <td><%=  link_to t('edit'), edit_guestbook_path(guestbook), class: 'btn btn-info' if current_user && current_user.is_admin %></td>
        <td><%= link_to t('destroy'), guestbook, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' if current_user && current_user.is_admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_guestbook_message') , new_guestbook_path,  class: 'btn btn-info' %>

app/views/guestbooks/new.html.erb
<h1>New guestbook</h1>

<%= render 'form' %>

<%= link_to 'Back', guestbooks_path %>

app/views/guestbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @guestbook.message %>
</p>

<p>
  <strong>Name:</strong>
  <%= @guestbook.name %>
</p>

<%= link_to 'Edit', edit_guestbook_path(@guestbook) %> |
<%= link_to 'Back', guestbooks_path, 'data-no-turbolink' => true  %>