config/routes.rb
Blog::Application.routes.draw do

  get "sessions/new"
  get "users/new"
  get 'links', to: 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  resources :baskets

  resources :products do
    collection do
      post 'addtobasket'
    end
  end
  resources :posts
  resources :guestbooks

  get "home/index"

   resources :home
   root 'home#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  require 'RMagick'
  def save_image (image)
    return if image.nil?

    # write image
    name = DateTime.now.to_i.to_s + '_' + image.original_filename
    directory = Rails.root + "app/assets/images"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(image.read) }

    # write image's thumbnail
    thumb = Magick::Image.read(directory + name).first
    thumb.crop_resized!(75, 75, Magick::NorthGravity)
    thumb.write (directory.to_s + '/thumb_' + name.to_s)

    # update names to model
    self.image_name = name
    self.image_name_thumb = 'thumb_' + name.to_s
    true
 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    #save image to server path
    @product.save_image (params[:product][:image])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    #save image to server path
    @product.save_image (params[:product][:image])

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def addtobasket
    respond_to do |format|
      format.js
      format.json { render :json => {name: 'test'}, :status => :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :in_stock_count, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :in_stock_count %><br>
    <%= f.number_field :in_stock_count %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>In stock count</th>
      <th>Description</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.price %></td>
        <td><%= product.in_stock_count %></td>
        <td><%= product.description %></td>
        <td><%= image_tag (asset_path product.image_name_thumb), {:class => 'imageThumb', :href => (asset_path product.image_name)} %></td>
        <td><%= link_to 'Add to basket', addtobasket_products_url, {:class => 'addToBasket' } %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>
<p id="notice"><%= notice %></p>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>In stock count:</strong>
  <%= @product.in_stock_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= image_tag (asset_path @product.image_name) %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>