config/routes.rb
Blog::Application.routes.draw do

  get "sessions/new"
  get "users/new"
  get 'links', to: 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  resources :baskets

  resources :products do
    collection do
      post 'addtobasket'
    end
  end
  resources :posts
  resources :guestbooks

  get "home/index"

   resources :home
   root 'home#index'

  

end

app/models/basket.rb
class Basket < ActiveRecord::Base
end

app/models/guestbook.rb
class Guestbook < ActiveRecord::Base
end

app/models/guestbookmessage.rb
class Guestbookmessage < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  require 'RMagick'
  def save_image (image)
    return if image.nil?

    # write image
    name = DateTime.now.to_i.to_s + '_' + image.original_filename
    directory = Rails.root + "app/assets/images"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(image.read) }

    # write image's thumbnail
    thumb = Magick::Image.read(directory + name).first
    thumb.crop_resized!(75, 75, Magick::NorthGravity)
    thumb.write (directory.to_s + '/thumb_' + name.to_s)

    # update names to model
    self.image_name = name
    self.image_name_thumb = 'thumb_' + name.to_s
    true
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates :password, presence: true

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, message: 'fsdfsdfs'
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      #redirect_to user_path(@user), :notice => "signed up!"
      redirect_to log_in_path, :notice => "sign up successful, you may now log in."
    else
     # render new
      flash[:error] = "User save failed"
      redirect_to :back
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:password, :email, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-warning"
    end
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/guestbook_helper.rb
module GuestbookHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <h6>
    <p>© 2014 Antti Matikainen </p>
  </h6>
</footer>

app/views/layouts/_log_in.html.erb
<ul class="nav navbar-nav pull-right">
  <li>
    <% if current_user %>
        <%= link_to "Log out", log_out_path %>
    <% else %>
        <%= link_to "Sign up", sign_up_path %>
    <% end %>
  </li>
  <li>
    <% if current_user == nil %>
        <%= link_to "log in", log_in_path %>
    <% end %>
  </li>
  <li>
    <% if current_user %>
        Logged in as <%= current_user.email %>
    <% end %>
  </li>
</ul>

app/views/layouts/_side_nav.html.erb
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
  <div class="list-group">
    <%= link_to root_path, class: 'list-group-item' do %>
        <i class="fa fa-home"><%= t('home') %></i>
    <% end %>
    <%= link_to links_path, class: 'list-group-item' do %>
        <i class="fa fa-tags"><%= t('links') %></i>
    <% end %>

  </div>
</div>

app/views/layouts/_top_nav.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Sisällysluettelo</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Antti Matikainen", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to root_path do %>
              <i class="fa fa-home"><%= t('home') %></i>
          <% end %>
        </li>
        <li>
          <%= link_to guestbooks_path, 'data-no-turbolink' => true do %>
              <i class="fa fa-book"><%= t('guestbook') %></i>
          <% end %>
        </li>
      </ul>

      <%= render 'layouts/log_in' %>

    </div>
    <!-- /.nav-collapse -->
  </div>
  <!-- /.container -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/top_nav' %>

<!-- /.navbar -->
<div class="container">
  <div class="row row-offcanvas row-offcanvas-right">
    <div id="content" class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Sisällysluettelo</button>
      </p>
      <%= yield %>
    </div>
    <!--/span-->

    <%= render 'layouts/side_nav' %>
    <!--/span-->
  </div>
  <!--/row-->
  <%= render 'layouts/footer' %>
</div>
<!--/.container-->

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>